name: Linux - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
      - name: Descargar e instalar dependencias
        run: |
          wget -O Downloads.sh "https://www.dropbox.com/scl/fi/xxxxx/Downloads.sh?dl=1"
          chmod +x Downloads.sh
          ./Downloads.sh

      - name: Iniciar sesión en AnyDesk (ejemplo)
        run: |
          chmod +x show.sh
          ./show.sh

      - name: Contador de tiempo
        run: python3 time.py
